### ISSUE TITLE
Configuration de Docker Compose pour Orchestrer tous les Services

### ISSUE THREAD

**Issue by benoit-bremaud** [benoit-bremaud/plateforme-safebase#27]
**Description :**  
L'objectif de cette tâche est de configurer un fichier **Docker Compose** pour orchestrer les différents services de l'application SafeBase : le backend (Fastify), le frontend (Angular), et la base de données (MySQL). Docker Compose permettra de lancer l'ensemble des services en une seule commande, garantissant une configuration cohérente entre les différents containers. Cette configuration doit inclure la gestion des réseaux Docker, des volumes pour la persistance des données, et l'orchestration des dépendances (ex. : le backend dépend de la base de données).

**Branche associée :**  
`docker/docker-compose-setup`

---

#### **1. Création du Fichier `docker-compose.yml`**

- [ ] **Définir les services pour le backend, le frontend, et MySQL :**
  - Créer un fichier `docker-compose.yml` avec les services suivants :
    - `backend` : Exécuter le service backend Fastify.
    - `frontend` : Exécuter le service frontend Angular.
    - `db` : Configurer et exécuter MySQL en tant que base de données.
  
- [ ] **Configurer les réseaux Docker pour la communication entre les services :**
  - S'assurer que les services communiquent correctement entre eux (ex. : le backend doit pouvoir accéder à MySQL).

- [ ] **Exemple de fichier `docker-compose.yml` :**
  ```yaml
  version: '3.8'
  services:
    backend:
      build: ./backend
      ports:
        - "3000:3000"
      depends_on:
        - db
      networks:
        - safebase-net

    frontend:
      build: ./frontend
      ports:
        - "4200:80"
      networks:
        - safebase-net

    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: safebase_db
        MYSQL_USER: safebase_user
        MYSQL_PASSWORD: user_password
      volumes:
        - ./mysql-data:/var/lib/mysql
      ports:
        - "3306:3306"
      networks:
        - safebase-net

  networks:
    safebase-net:
      driver: bridge
  ```

#### **2. Configuration des Volumes pour la Persistance des Données**

- [ ] **Configurer des volumes pour le service MySQL :**
  - Ajouter un volume Docker pour la persistance des données MySQL afin de garantir que les données de la base de données ne sont pas perdues lors de l'arrêt des containers.

- [ ] **Optionnel : Ajouter des volumes pour le frontend et le backend si nécessaire :**
  - Si des configurations spécifiques nécessitent des volumes pour le frontend ou le backend (par exemple pour stocker des fichiers générés), les inclure dans la configuration Docker Compose.

#### **3. Configuration des Variables d'Environnement pour chaque Service**

- [ ] **Configurer les variables d'environnement pour le service MySQL :**
  - Ajouter les variables d'environnement nécessaires pour sécuriser la base de données (ex. : `MYSQL_ROOT_PASSWORD`, `MYSQL_DATABASE`, etc.).

- [ ] **Configurer les variables d'environnement pour le backend :**
  - Ajouter des variables d'environnement pour le backend (ex. : configuration de la connexion à la base de données).

#### **4. Tests et Validation des Services Docker Compose**

- [ ] **Lancer Docker Compose en local :**
  - Exécuter la commande `docker-compose up` pour démarrer tous les services (backend, frontend, MySQL).
  
- [ ] **Tester la communication entre les services :**
  - Valider que le backend peut interagir avec la base de données MySQL (ex. : exécuter des requêtes CRUD via l'API backend).
  - Vérifier que le frontend Angular peut se connecter au backend et afficher les données récupérées de l'API.

- [ ] **Valider le bon fonctionnement des volumes et la persistance des données :**
  - Tester que les données MySQL sont correctement persistées même après l'arrêt et le redémarrage des containers.

#### **5. Documentation**

- [ ] **Documenter la configuration Docker Compose dans le dépôt GitHub :**
  - Ajouter une section au `README.md` expliquant comment utiliser Docker Compose pour démarrer l'application SafeBase.
  - Inclure des instructions sur la personnalisation des variables d'environnement et des volumes si nécessaire.

---

### **Critères d'acceptation :**
- [ ] Le fichier `docker-compose.yml` est créé et configure correctement les services backend, frontend, et MySQL.
- [ ] Les services communiquent correctement entre eux via des réseaux Docker.
- [ ] Les données MySQL sont persistantes grâce aux volumes configurés.
- [ ] L'application SafeBase peut être démarrée en une seule commande avec Docker Compose (`docker-compose up`).
- [ ] La documentation est à jour et inclut les instructions pour utiliser Docker Compose.
